Repository TheSmartCooking/Front-end, pull requests merged in 2025-01, with the labels that each got.

#14 Add logout functionality
  authentication.html
  css/authentication.css
  css/index.css
  css/main.css
  css/profile.css
  index.html
  javascript/header.js
  javascript/index.js
  javascript/main.js
  javascript/profile.js
  profile.html
Labels: feature

#15 Migrate to Nuxt.js
  .dockerignore
  .gitattributes
  .github/workflows/super-linter.yml
  .gitignore
  Dockerfile
  README.md
  app.vue
  assets/icons/eye-off.svg
  assets/icons/eye.svg
  assets/icons/home.svg
  assets/icons/mail-question.svg
  assets/icons/user.svg
  assets/styles/variables.css
  authentication.html
  components/ButtonHome.vue
  components/Comment.vue
  components/Footer.vue
  components/Header.vue
  components/LoadingSpinner.vue
  components/Recipe.vue
  components/RecipeCard.vue
  components/SearchBar.vue
  components/authentication/Login.vue
  components/authentication/Register.vue
  css/authentication.css
  css/index.css
  css/main.css
  css/modal.css
  css/profile.css
  index.html
  javascript/authentication.js
  javascript/footer.js
  javascript/header.js
  javascript/index.js
  javascript/main.js
  javascript/modal.js
  javascript/profile.js
  nuxt.config.ts
  package-lock.json
  package.json
  pages/account.vue
  pages/contact.vue
  pages/index.vue
  pages/login.vue
  pages/recipe/[id].vue
  pages/recipe/index.vue
  profile.html
  public/default-recipe.png
  public/favicon.ico
  public/robots.txt
  server/tsconfig.json
  tsconfig.json
  utils/fetch.js
  utils/spinner.js
Labels: migration

#18 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#20 Refactor code style for consistency and readability across components
  .github/workflows/super-linter.yml
  components/ButtonHome.vue
  components/Footer.vue
  components/Header.vue
  components/LoadingSpinner.vue
  components/Recipe.vue
  components/RecipeCard.vue
  components/SearchBar.vue
  components/authentication/Login.vue
  pages/account.vue
  pages/contact.vue
  pages/index.vue
  pages/login.vue
Labels: refactor
